#!/usr/bin/env bash
cd "$(dirname "$0")" || exit 1
while sleep 1; do
	LAST="$(stat -c %Y "$XDG_RUNTIME_DIR/lasttabmove")"
	NOW="$(date +%s)"
	if [[ -z "$LAST" ]]; then
		touch "$XDG_RUNTIME_DIR/lasttabmove"
	else
		if [[ $(($NOW - $LAST)) -ge 20 ]]; then
			./tab-right
		fi
	fi
done
