#!/usr/bin/env bash
set -x
N=11
LAST_LINES=""
while read line; do
  LAST_LINES=$(echo -e "$LAST_LINES\n$line" | tail -n$N)
  if echo -n "$LAST_LINES" | tr '\n' : | grep -qE '^gamepad_up:gamepad_up:gamepad_down:gamepad_down:gamepad_left:gamepad_right:gamepad_left:gamepad_right:gamepad_b:gamepad_a:gamepad_start$'; then
    TMP_FILE=$(mktemp)
    cat /dev/fb0 > $TMP_FILE
    /home/pi/life-framebuffer/a.out &
    sleep 5
    kill $!
    cat $TMP_FILE > /dev/fb0
    rm $TMP_FILE
  fi
  echo "$line"
done
