#!/usr/bin/env python3
import os
import time

filename = os.environ["XDG_RUNTIME_DIR"] + "/lasttabmove"
if not os.path.exists(filename):
	with open(filename, "w") as f:
		pass

now = time.time()
last = os.stat(filename).st_mtime

if last > now:
	print("paused")
	os.utime(filename, (0, now + 900))
else:
	print("not paused")
	os.utime(filename, (0, now))
