#!/usr/bin/env python3
from flask import Flask
import requests

app = Flask(__name__)

@app.route('/')
def index():
    with open("/home/pi/bus-timetables/index.html", "rb") as f:
        return f.read()

@app.route('/api/stop/<int:stop_id>')
def proxy_stop(stop_id):
    res = requests.get(f"https://lothianapi.co.uk/departureBoards/website?stops={stop_id}")
    return res.json()

@app.route('/api/colors')
def proxy_colors():
    res = requests.get(f"https://lothianapi.com/routes/all")
    return res.json()

app.run()
