#!/usr/bin/env python3
from flask import Flask
import requests

app = Flask(__name__)

@app.route('/')
def index():
    with open("/home/pi/bus-timetables/index.html", "rb") as f:
        return f.read()

@app.route('/api/stop/<int:stop_id>')
def proxy_stop(stop_id):
    res = requests.get(f"https://tfe-opendata.com/api/v1/live_bus_times/{stop_id}")
    return res.json()

@app.route('/api/colors')
def proxy_colors():
    with open("/home/pi/bus-timetables/routes.json", "rb") as f:
        return f.read()

app.run()
